sudo: required
language: node_js
node_js:
  - 6.9.4
addons:
  firefox: "48.0"
before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.11.1/geckodriver-v0.11.1-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.11.1-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver
install:
- npm install
- npm install selenium-webdriver
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - ./node_modules/protractor/bin/webdriver-manager update
script:
- npm run build
- npm run test
- node server.test.js &
- npm run e2e
cache:
  directories:
    - node_modules
